DROP SCHEMA IF EXISTS "shopdb" CASCADE;
CREATE SCHEMA IF NOT EXISTS "shopdb";
SET SCHEMA "shopdb";
DROP TABLE IF EXISTS "shopdb"."USERS" CASCADE;
CREATE TABLE IF NOT EXISTS "shopdb"."users" (
                                                "id" number NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                                "email" varchar(256) NOT NULL,
                                                "password_hash" blob NOT NULL,
                                                "salt" varchar(16) NOT NULL,
                                                "role" varchar(16) NOT NULL,
                                                "create_date" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                                "last_update" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                                PRIMARY KEY ("id"),
                                                CONSTRAINT "email_UNIQUE"
                                                    UNIQUE ("email")
);
DROP TABLE IF EXISTS "shopdb"."categories" CASCADE;
CREATE TABLE IF NOT EXISTS "shopdb"."categories" (
                                                     "id" number NOT NULL,
                                                     "name" varchar(256) NOT NULL,
                                                     "parent_id" number NOT NULL,
                                                     "create_date" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                                     "last_update" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                                     PRIMARY KEY ("id"),
                                                     CONSTRAINT "name_UNIQUE"
                                                         UNIQUE ("name"),
                                                     CONSTRAINT "fk_categories_categories1"
                                                         FOREIGN KEY ("parent_id")
                                                             REFERENCES "categories" ("id") ON DELETE CASCADE ON UPDATE NO ACTION
);
DROP TABLE IF EXISTS "shopdb"."products" CASCADE;
CREATE TABLE IF NOT EXISTS "shopdb"."products" (
                                                   "id" number NOT NULL,
                                                   "name" varchar(256) NOT NULL,
                                                   "picture" varchar(64) NOT NULL,
                                                   "color" varchar(16) NOT NULL,
                                                   "description" varchar(4096) NULL,
                                                   "price" double NOT NULL,
                                                   "amount" bigint NOT NULL DEFAULT 0,
                                                   "category_id" number NOT NULL,
                                                   "create_date" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                                   "last_update" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                                   PRIMARY KEY ("id"),
                                                   CONSTRAINT "fk_products_categories1"
                                                       FOREIGN KEY ("category_id")
                                                           REFERENCES "categories" ("id") ON DELETE CASCADE ON UPDATE NO ACTION
);
DROP TABLE IF EXISTS "shopdb"."orders" CASCADE;
CREATE TABLE IF NOT EXISTS "shopdb"."orders" (
                                                 "id" number NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                                 "user_id" number NOT NULL,
                                                 "total" double NOT NULL DEFAULT 0,
                                                 "status" varchar(16) NOT NULL DEFAULT 'REGISTERED',
                                                 "create_date" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                                 "last_update" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                                 PRIMARY KEY ("id"),
                                                 CONSTRAINT "fk_orders_users1"
                                                     FOREIGN KEY ("user_id")
                                                         REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE NO ACTION);
DROP TABLE IF EXISTS "shopdb"."order_has_product" CASCADE;
CREATE TABLE IF NOT EXISTS "shopdb"."order_has_product" (
                                                            "order_id" number NOT NULL,
                                                            "product_id" number NOT NULL,
                                                            "count" bigint NOT NULL,
                                                            "price" double NOT NULL,
                                                            PRIMARY KEY (
                                                                         "order_id",
                                                                         "product_id"
                                                                ),
                                                            CONSTRAINT "fk_cart_has_products_cart1"
                                                                FOREIGN KEY ("order_id")
                                                                    REFERENCES "orders" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION,
                                                            CONSTRAINT "fk_cart_has_products_products1"
                                                                FOREIGN KEY ("product_id")
                                                                    REFERENCES "products" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION
);
DROP TABLE IF EXISTS "shopdb"."addresses" CASCADE;
CREATE TABLE IF NOT EXISTS "shopdb"."addresses" (
                                                    "id" number NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                                    "country" varchar(128) NOT NULL,
                                                    "city" varchar(128) NOT NULL,
                                                    "building" varchar(16) NOT NULL,
                                                    "apartment" bigint NULL,
                                                    "create_date" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                                    "last_update" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                                    PRIMARY KEY ("id"),
                                                    CONSTRAINT "country_city_building__apartment_UNIQUE"
                                                        UNIQUE (
                                                                "country",
                                                                "city",
                                                                "building",
                                                                "apartment"
                                                            )
);
DROP TABLE IF EXISTS "shopdb"."blocked_users" CASCADE;
CREATE TABLE IF NOT EXISTS "shopdb"."blocked_users" (
                                                        "user_id" number NOT NULL,
                                                        "begin_date" date NOT NULL,
                                                        PRIMARY KEY ("user_id"),
                                                        CONSTRAINT "fk_blocked_users_users1"
                                                            FOREIGN KEY ("user_id")
                                                                REFERENCES "users" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION
);